# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  python:
    paths:
      - python/vesper/
    carryforward: true
  rust:
    paths:
      - rust/
    carryforward: true

ignore:
  - "python/tests/**/*"
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/target/**"
